In [2]:
%pip install ucimlrepo openpyxl

Requirement already satisfied: ucimlrepo in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (0.0.7)
Requirement already satisfied: openpyxl in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: pandas>=1.0.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2025.6.15)
Requirement already satisfied: et-xmlfile in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ronal\appdata\roaming\python\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\ronal\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd

## Atividade 2 - Imputação de valores faltantes

### Dataset 1
Link: archive.ics.uci.edu/ml/datasets/adult

In [4]:
adult = fetch_ucirepo(id=2) 
  
X = adult.data.features 
y = adult.data.targets 
  
df_adult = pd.concat([X, y], axis=1)

In [5]:
df_adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df_adult.isnull().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
income              0
dtype: int64

In [7]:
cat_cols = df_adult.select_dtypes(exclude='number').columns
df_adult[cat_cols] = df_adult[cat_cols].fillna("None")

In [10]:
df_adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

### Dataset 2
Link: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [16]:
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
  
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets 

df_breast_cancer_diagnostic = pd.concat([X, y], axis=1)

In [21]:
df_breast_cancer_diagnostic.head()

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

In [20]:
df_breast_cancer_diagnostic.isnull().sum()

radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
Diagnosis             0
dtype: int64

### Dataset 3
Link: archive.ics.uci.edu/ml/datasets/credit+approval

In [23]:
credit_approval = fetch_ucirepo(id=27) 
  
X = credit_approval.data.features 
y = credit_approval.data.targets 
  
df_credit_approval = pd.concat([X, y], axis=1)

In [28]:
df_credit_approval

     A15    A14 A13 A12  A11 A10 A9    A8  A7  A6 A5 A4      A3     A2 A1 A16
0      0  202.0   g   f    1   t  t  1.25   v   w  g  u   0.000  30.83  b   +
1    560   43.0   g   f    6   t  t  3.04   h   q  g  u   4.460  58.67  a   +
2    824  280.0   g   f    0   f  t  1.50   h   q  g  u   0.500  24.50  a   +
3      3  100.0   g   t    5   t  t  3.75   v   w  g  u   1.540  27.83  b   +
4      0  120.0   s   f    0   f  t  1.71   v   w  g  u   5.625  20.17  b   +
..   ...    ...  ..  ..  ...  .. ..   ...  ..  .. .. ..     ...    ... ..  ..
685    0  260.0   g   f    0   f  f  1.25   h   e  p  y  10.085  21.08  b   -
686  394  200.0   g   t    2   t  f  2.00   v   c  g  u   0.750  22.67  a   -
687    1  200.0   g   t    1   t  f  2.00  ff  ff  p  y  13.500  25.25  a   -
688  750  280.0   g   f    0   f  f  0.04   v  aa  g  u   0.205  17.92  b   -
689    0    0.0   g   t    0   f  f  8.29   h   c  g  u   3.375  35.00  b   -

[690 rows x 16 columns]

In [29]:
df_credit_approval.isnull().sum()

A15     0
A14    13
A13     0
A12     0
A11     0
A10     0
A9      0
A8      0
A7      9
A6      9
A5      6
A4      6
A3      0
A2     12
A1     12
A16     0
dtype: int64

#### Inserindo dados faltantes com a média

In [30]:
df_credit_approval_mean = df_credit_approval.copy()

In [31]:
num_cols = df_credit_approval_mean.select_dtypes(include='number').columns

for col in num_cols:
  mean_value = df_credit_approval_mean[col].mean()
  print(f"Coluna: {col}, Média: {mean_value}")
  df_credit_approval_mean[col].fillna(mean_value, inplace=True)

Coluna: A15, Média: 1017.3855072463768
Coluna: A14, Média: 184.01477104874445
Coluna: A11, Média: 2.4
Coluna: A8, Média: 2.223405797101449
Coluna: A3, Média: 4.758724637681159
Coluna: A2, Média: 31.56817109144543

C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\185849992.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_credit_approval_mean[col].fillna(mean_value, inplace=True)

In [32]:
df_credit_approval_mean[df_credit_approval_mean['A14'] == 184.01477104874445]

,A15,A14,A13,A12,A11,A10,A9,A8,A7,A6,A5,A4,A3,A2,A1,A16
71,0,184.014771,g,t,0,f,t,12.500,bb,d,g,u,4.000,34.830000,b,-
202,600,184.014771,g,f,6,t,t,2.250,v,c,g,u,2.750,24.830000,b,+
206,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,71.580000,a,+
243,26726,184.014771,g,f,5,t,t,2.710,v,q,g,u,7.500,18.750000,a,+
270,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,37.580000,b,+
278,0,184.014771,g,f,0,f,f,0.000,ff,ff,p,y,13.500,24.580000,b,-
330,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,20.420000,b,-
406,18,184.014771,g,f,2,t,f,0.165,v,k,p,y,8.125,40.330000,a,-
445,5200,184.014771,g,f,0,f,f,0.000,ff,ff,g,u,11.250,31.568171,a,-
456,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,34.580000,b,-
592,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,23.170000,b,+
622,0,184.014771,p,f,0,f,f,0.000,NaN,NaN,NaN,NaN,0.000,25.580000,a,+
626,0,184.014771,g,t,0,f,f,0.165,bb,i,p,y,7.835,22.000000,b,-

#### Inserindo dados faltantes com a moda

In [33]:
df_credit_approval_mode = df_credit_approval.copy()

In [34]:
num_cols = df_credit_approval_mode.select_dtypes(include='number').columns

for col in num_cols:
  mode_value = df_credit_approval_mode[col].mode()[0]
  print(f"Coluna: {col}, Moda: {mode_value}")
  df_credit_approval_mode[col].fillna(mode_value, inplace=True)

Coluna: A15, Moda: 0
Coluna: A14, Moda: 0.0
Coluna: A11, Moda: 0
Coluna: A8, Moda: 0.0
Coluna: A3, Moda: 1.5
Coluna: A2, Moda: 22.67

C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3008967538.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_credit_approval_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3008967538.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_credit_approval_mode[col].fillna(mode_value, inplace=True)

In [35]:
df_credit_approval_mean[df_credit_approval_mean['A14'] == 0]

      A15  A14 A13 A12  A11 A10 A9     A8  A7  A6 A5 A4      A3     A2 A1 A16
12      0  0.0   g   t    0   f  t  1.000   v   k  g  u   6.000  38.25  a   +
13   2690  0.0   g   f    0   f  f  0.040   v   k  g  u   6.040  48.08  b   +
14      0  0.0   g   t    7   t  t  5.000   v   q  g  u  10.500  45.83  a   +
18      0  0.0   g   t    0   f  t  0.665   h   d  g  u   0.250  21.83  b   +
22   1260  0.0   g   t    6   t  t  7.875   v   c  g  u   8.000  47.75  a   +
..    ...  ...  ..  ..  ...  .. ..    ...  ..  .. .. ..     ...    ... ..  ..
665     0  0.0   g   f    0   f  f  0.040   v   m  p  y   0.040  31.83  b   -
671     2  0.0   g   f    0   f  f  0.500   v  cc  g  u  12.835  25.83  b   -
678    50  0.0   g   f    0   f  f  0.000  ff  ff  g  u  10.210  17.92  a   -
679     0  0.0   g   f    0   f  f  0.000   v   c  g  u   1.250  20.08  a   -
689     0  0.0   g   t    0   f  f  8.290   h   c  g  u   3.375  35.00  b   -

[132 rows x 16 columns]

### Dataset 4
Link: https://www.kaggle.com/code/kerneler/starter-ames-housing-fb60970c-d

In [36]:
df_ames_housing = pd.read_excel('./datasets/AmesHousing.xls', engine="xlrd")

In [37]:
df_ames_housing

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [38]:
df_ames_housing.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [39]:
df_ames_housing.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [40]:
df_ames_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [43]:
missing_counts = df_ames_housing.isnull().sum().sort_values(ascending=False)
missing_counts[missing_counts > 0]

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Cond        159
Garage Finish      159
Garage Yr Blt      159
Garage Qual        159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
Bsmt Qual           80
Bsmt Cond           80
BsmtFin Type 1      80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 1         1
Garage Cars          1
Electrical           1
Total Bsmt SF        1
Bsmt Unf SF          1
BsmtFin SF 2         1
Garage Area          1
dtype: int64

#### Inserindo dados com a média

In [47]:
df_ames_housing_mean = df_ames_housing.copy()

In [48]:
num_cols = df_ames_housing_mean.select_dtypes(include='number').columns

for col in num_cols:
  mean_value = df_ames_housing_mean[col].mean()
  print(f"Coluna: {col}, Média: {mean_value}")
  df_ames_housing_mean[col].fillna(mean_value, inplace=True)

Coluna: Order, Média: 1465.5
Coluna: PID, Média: 714464496.9887372
Coluna: MS SubClass, Média: 57.38737201365188
Coluna: Lot Frontage, Média: 69.22459016393442
Coluna: Lot Area, Média: 10147.921843003413
Coluna: Overall Qual, Média: 6.0948805460750854
Coluna: Overall Cond, Média: 5.563139931740614
Coluna: Year Built, Média: 1971.3563139931741
Coluna: Year Remod/Add, Média: 1984.266552901024
Coluna: Mas Vnr Area, Média: 101.8968008255934
Coluna: BsmtFin SF 1, Média: 442.6295664049164
Coluna: BsmtFin SF 2, Média: 49.72243086377603
Coluna: Bsmt Unf SF, Média: 559.2625469443497
Coluna: Total Bsmt SF, Média: 1051.6145442130419
Coluna: 1st Flr SF, Média: 1159.5576791808874
Coluna: 2nd Flr SF, Média: 335.45597269624574
Coluna: Low Qual Fin SF, Média: 4.67679180887372
Coluna: Gr Liv Area, Média: 1499.6904436860068
Coluna: Bsmt Full Bath, Média: 0.43135245901639346
Coluna: Bsmt Half Bath, Média: 0.061133879781420764
Coluna: Full Bath, Média: 1.5665529010238908
Coluna: Half Bath, Média: 0.3795221843003413
Coluna: Bedroom AbvGr, Média: 2.8542662116040955
Coluna: Kitchen AbvGr, Média: 1.0443686006825939
Coluna: TotRms AbvGrd, Média: 6.443003412969284
Coluna: Fireplaces, Média: 0.5993174061433447
Coluna: Garage Yr Blt, Média: 1978.1324431613136
Coluna: Garage Cars, Média: 1.7668146124957322
Coluna: Garage Area, Média: 472.8197336975077
Coluna: Wood Deck SF, Média: 93.75187713310581
Coluna: Open Porch SF, Média: 47.53344709897611
Coluna: Enclosed Porch, Média: 23.01160409556314
Coluna: 3Ssn Porch, Média: 2.592491467576792
Coluna: Screen Porch, Média: 16.002047781569967
Coluna: Pool Area, Média: 2.243344709897611
Coluna: Misc Val, Média: 50.63515358361775
Coluna: Mo Sold, Média: 6.216040955631399
Coluna: Yr Sold, Média: 2007.790443686007
Coluna: SalePrice, Média: 180796.0600682594

C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3191968445.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mean[col].fillna(mean_value, inplace=True)

In [51]:
df_ames_housing_mean[df_ames_housing_mean['Lot Frontage'] == 69.22459016393442]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
11,12,527165230,20,RL,69.22459,7980,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,Shed,500,3,2010,WD,Normal,185000
14,15,527182190,120,RL,69.22459,6820,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,212000
22,23,527368020,60,FV,69.22459,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,216000
23,24,527402200,20,RL,69.22459,11241,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
24,25,527402250,20,RL,69.22459,12537,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,149900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2894,2895,916326010,20,RL,69.22459,16669,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,1,2006,WD,Normal,228000
2897,2898,916403130,60,RL,69.22459,11170,Pave,NaN,IR2,Lvl,...,0,NaN,GdPrv,NaN,0,4,2006,WD,Normal,250000
2898,2899,916460070,20,RL,69.22459,8098,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,202000
2912,2913,923226150,90,RL,69.22459,11836,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2006,WD,Normal,146500
2926,2927,923276100,20,RL,69.22459,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000

#### Inserindo dados com a moda

In [52]:
df_ames_housing_mode = df_ames_housing.copy()

In [53]:
num_cols = df_ames_housing_mode.select_dtypes(include='number').columns

for col in num_cols:
  mode_value = df_ames_housing_mode[col].mode()[0]
  print(f"Coluna: {col}, Moda: {mode_value}")
  df_ames_housing_mode[col].fillna(mode_value, inplace=True)

Coluna: Order, Moda: 1
Coluna: PID, Moda: 526301100
Coluna: MS SubClass, Moda: 20
Coluna: Lot Frontage, Moda: 60.0
Coluna: Lot Area, Moda: 9600
Coluna: Overall Qual, Moda: 5
Coluna: Overall Cond, Moda: 5
Coluna: Year Built, Moda: 2005
Coluna: Year Remod/Add, Moda: 1950
Coluna: Mas Vnr Area, Moda: 0.0
Coluna: BsmtFin SF 1, Moda: 0.0
Coluna: BsmtFin SF 2, Moda: 0.0
Coluna: Bsmt Unf SF, Moda: 0.0
Coluna: Total Bsmt SF, Moda: 0.0
Coluna: 1st Flr SF, Moda: 864
Coluna: 2nd Flr SF, Moda: 0
Coluna: Low Qual Fin SF, Moda: 0
Coluna: Gr Liv Area, Moda: 864
Coluna: Bsmt Full Bath, Moda: 0.0
Coluna: Bsmt Half Bath, Moda: 0.0
Coluna: Full Bath, Moda: 2
Coluna: Half Bath, Moda: 0
Coluna: Bedroom AbvGr, Moda: 3
Coluna: Kitchen AbvGr, Moda: 1
Coluna: TotRms AbvGrd, Moda: 6
Coluna: Fireplaces, Moda: 0
Coluna: Garage Yr Blt, Moda: 2005.0
Coluna: Garage Cars, Moda: 2.0
Coluna: Garage Area, Moda: 0.0
Coluna: Wood Deck SF, Moda: 0
Coluna: Open Porch SF, Moda: 0
Coluna: Enclosed Porch, Moda: 0
Coluna: 3Ssn Porch, Moda: 0
Coluna: Screen Porch, Moda: 0
Coluna: Pool Area, Moda: 0
Coluna: Misc Val, Moda: 0
Coluna: Mo Sold, Moda: 6
Coluna: Yr Sold, Moda: 2007
Coluna: SalePrice, Moda: 135000

C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)
C:\Users\ronal\AppData\Local\Temp\ipykernel_3296\3509719169.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ames_housing_mode[col].fillna(mode_value, inplace=True)