In [1]:
%pip install ucimlrepo openpyxl scikit-learn

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: ucimlrepo in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (0.0.7)
Requirement already satisfied: openpyxl in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: scikit-learn in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (1.7.1)
Requirement already satisfied: pandas>=1.0.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2025.6.15)
Requirement already satisfied: et-xmlfile in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ronal\appdata\roaming\python\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ronal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\ronal\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from ucimlrepo import fetch_ucirepo 
import pandas as pd

Aluno: Ronald Carvalho Boadana

## Atividade 4 - Escalonamento de variáveis numéricas (StandardScaler e MinMaxScaler)

### Dataset 1
Link: archive.ics.uci.edu/ml/datasets/adult

In [5]:
adult = fetch_ucirepo(id=2) 
  
X = adult.data.features 
y = adult.data.targets 
  
df_adult = pd.concat([X, y], axis=1)

In [6]:
df_adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
num_cols = ['age', 'fnlwgt', 'capital-gain', 'capital-loss', 'hours-per-week']

In [12]:
df_num = df_adult[num_cols].copy()

In [13]:
scaler_std = StandardScaler()
df_std = pd.DataFrame(
    scaler_std.fit_transform(df_num),
    columns=[f'padro_{col}' for col in num_cols],
    index=df_adult.index
)

In [14]:
scaler_minmax = MinMaxScaler()
df_minmax = pd.DataFrame(
    scaler_minmax.fit_transform(df_num),
    columns=[f'norm_{col}' for col in num_cols],
    index=df_adult.index
)

In [17]:
df_final = pd.concat([df_std, df_minmax], axis=1)

In [18]:
df_final

,padro_age,padro_fnlwgt,padro_capital-gain,padro_capital-loss,padro_hours-per-week,norm_age,norm_fnlwgt,norm_capital-gain,norm_capital-loss,norm_hours-per-week
0,0.025996,-1.061979,0.146932,-0.217127,-0.034087,0.301370,0.044131,0.021740,0.0,0.397959
1,0.828308,-1.007104,-0.144804,-0.217127,-2.213032,0.452055,0.048052,0.000000,0.0,0.122449
2,-0.046942,0.246034,-0.144804,-0.217127,-0.034087,0.287671,0.137581,0.000000,0.0,0.397959
3,1.047121,0.426663,-0.144804,-0.217127,-0.034087,0.493151,0.150486,0.000000,0.0,0.397959
4,-0.776316,1.408530,-0.144804,-0.217127,-0.034087,0.150685,0.220635,0.000000,0.0,0.397959
...,...,...,...,...,...,...,...,...,...,...
48837,0.025996,0.243884,-0.144804,-0.217127,-0.356894,0.301370,0.137428,0.000000,0.0,0.357143
48838,1.849433,1.247492,-0.144804,-0.217127,-0.034087,0.643836,0.209130,0.000000,0.0,0.397959
48839,-0.046942,1.754865,-0.144804,-0.217127,0.772930,0.287671,0.245379,0.000000,0.0,0.500000
48840,0.390683,-1.001612,0.587220,-0.217127,-0.034087,0.369863,0.048444,0.054551,0.0,0.397959
48841,-0.265754,-0.071174,-0.144804,-0.217127,1.579946,0.246575,0.114919,0.000000,0.0,0.602041

### Dataset 2
Link: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [19]:
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
  
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets 

df_breast_cancer_diagnostic = pd.concat([X, y], axis=1)

In [20]:
df_breast_cancer_diagnostic.head()

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

In [21]:
df_breast_cancer_diagnostic.columns

Index(['radius1', 'texture1', 'perimeter1', 'area1', 'smoothness1',
       'compactness1', 'concavity1', 'concave_points1', 'symmetry1',
       'fractal_dimension1', 'radius2', 'texture2', 'perimeter2', 'area2',
       'smoothness2', 'compactness2', 'concavity2', 'concave_points2',
       'symmetry2', 'fractal_dimension2', 'radius3', 'texture3', 'perimeter3',
       'area3', 'smoothness3', 'compactness3', 'concavity3', 'concave_points3',
       'symmetry3', 'fractal_dimension3', 'Diagnosis'],
      dtype='object')

In [22]:
num_cols = [col for col in df_breast_cancer_diagnostic.columns if col != 'Diagnosis']

In [23]:
df_num = df_breast_cancer_diagnostic[num_cols].copy()

In [24]:
scaler_std = StandardScaler()
df_std = pd.DataFrame(
    scaler_std.fit_transform(df_num),
    columns=[f'padro_{col}' for col in num_cols],
    index=df_breast_cancer_diagnostic.index
)

In [25]:
scaler_minmax = MinMaxScaler()
df_minmax = pd.DataFrame(
    scaler_minmax.fit_transform(df_num),
    columns=[f'norm_{col}' for col in num_cols],
    index=df_breast_cancer_diagnostic.index
)

In [28]:
df_final = pd.concat([df_std, df_minmax], axis=1)

In [29]:
df_final

,padro_radius1,padro_texture1,padro_perimeter1,padro_area1,padro_smoothness1,padro_compactness1,padro_concavity1,padro_concave_points1,padro_symmetry1,padro_fractal_dimension1,...,norm_radius3,norm_texture3,norm_perimeter3,norm_area3,norm_smoothness3,norm_compactness3,norm_concavity3,norm_concave_points3,norm_symmetry3,norm_fractal_dimension3
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,0.620776,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,0.606901,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,0.556386,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,0.248310,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,0.519744,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,...,0.623266,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,...,0.560655,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,...,0.393099,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,...,0.633582,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,...,0.054287,0.489072,0.043578,0.020497,0.124084,0.036043,0.000000,0.000000,0.257441,0.100682

### Dataset 3
Link: archive.ics.uci.edu/ml/datasets/credit+approval

In [42]:
credit_approval = fetch_ucirepo(id=27) 
  
X = credit_approval.data.features 
y = credit_approval.data.targets 
  
df_credit_approval = pd.concat([X, y], axis=1)

In [43]:
df_credit_approval

     A15    A14 A13 A12  A11 A10 A9    A8  A7  A6 A5 A4      A3     A2 A1 A16
0      0  202.0   g   f    1   t  t  1.25   v   w  g  u   0.000  30.83  b   +
1    560   43.0   g   f    6   t  t  3.04   h   q  g  u   4.460  58.67  a   +
2    824  280.0   g   f    0   f  t  1.50   h   q  g  u   0.500  24.50  a   +
3      3  100.0   g   t    5   t  t  3.75   v   w  g  u   1.540  27.83  b   +
4      0  120.0   s   f    0   f  t  1.71   v   w  g  u   5.625  20.17  b   +
..   ...    ...  ..  ..  ...  .. ..   ...  ..  .. .. ..     ...    ... ..  ..
685    0  260.0   g   f    0   f  f  1.25   h   e  p  y  10.085  21.08  b   -
686  394  200.0   g   t    2   t  f  2.00   v   c  g  u   0.750  22.67  a   -
687    1  200.0   g   t    1   t  f  2.00  ff  ff  p  y  13.500  25.25  a   -
688  750  280.0   g   f    0   f  f  0.04   v  aa  g  u   0.205  17.92  b   -
689    0    0.0   g   t    0   f  f  8.29   h   c  g  u   3.375  35.00  b   -

[690 rows x 16 columns]

In [44]:
df_credit_approval.columns

Index(['A15', 'A14', 'A13', 'A12', 'A11', 'A10', 'A9', 'A8', 'A7', 'A6', 'A5',
       'A4', 'A3', 'A2', 'A1', 'A16'],
      dtype='object')

In [48]:
num_cols = ['A15', 'A14', 'A11', 'A8', 'A3', 'A2']

In [49]:
df_num = df_credit_approval[num_cols].copy()

In [50]:
scaler_std = StandardScaler()
df_std = pd.DataFrame(
    scaler_std.fit_transform(df_num),
    columns=[f'padro_{col}' for col in num_cols],
    index=df_credit_approval.index
)

In [51]:
scaler_minmax = MinMaxScaler()
df_minmax = pd.DataFrame(
    scaler_minmax.fit_transform(df_num),
    columns=[f'norm_{col}' for col in num_cols],
    index=df_credit_approval.index
)

In [52]:
df_final = pd.concat([df_std, df_minmax], axis=1)

In [53]:
df_final

,padro_A15,padro_A14,padro_A11,padro_A8,padro_A3,padro_A2,norm_A15,norm_A14,norm_A11,norm_A8,norm_A3,norm_A2
0,-0.195413,0.103555,-0.288101,-0.291083,-0.956613,-0.061777,0.00000,0.1010,0.014925,0.043860,0.000000,0.256842
1,-0.087852,-0.811931,0.740830,0.244190,-0.060051,2.268118,0.00560,0.0215,0.089552,0.106667,0.159286,0.675489
2,-0.037144,0.552661,-0.493887,-0.216324,-0.856102,-0.591526,0.00824,0.1400,0.000000,0.052632,0.017857,0.161654
3,-0.194837,-0.483738,0.535044,0.456505,-0.647038,-0.312843,0.00003,0.0500,0.074627,0.131579,0.055000,0.211729
4,-0.195413,-0.368582,-0.493887,-0.153526,0.174141,-0.953898,0.00000,0.0600,0.000000,0.060000,0.200893,0.096541
...,...,...,...,...,...,...,...,...,...,...,...,...
685,-0.195413,0.437505,-0.493887,-0.291083,1.070704,-0.877742,0.00000,0.1300,0.000000,0.043860,0.360179,0.110226
686,-0.119736,0.092039,-0.082314,-0.066806,-0.805846,-0.744677,0.00394,0.1000,0.029851,0.070175,0.026786,0.134135
687,-0.195221,0.092039,-0.288101,-0.066806,1.757198,-0.528760,0.00001,0.1000,0.014925,0.070175,0.482143,0.172932
688,-0.051358,0.552661,-0.493887,-0.652915,-0.915403,-1.142198,0.00750,0.1400,0.000000,0.001404,0.007321,0.062707
689,-0.195413,-1.059515,-0.493887,1.814125,-0.278161,0.287205,0.00000,0.0000,0.000000,0.290877,0.120536,0.319549

### Dataset 4
Link: https://www.kaggle.com/code/kerneler/starter-ames-housing-fb60970c-d

In [57]:
df_ames_housing = pd.read_excel('./datasets/AmesHousing.xls', engine="xlrd")

In [58]:
df_ames_housing.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [59]:
df_ames_housing.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [60]:
num_cols = df_ames_housing.select_dtypes(include=['int64', 'float64']).columns.drop('SalePrice')

In [61]:
cat_cols = df_ames_housing.select_dtypes(include=['object']).columns.tolist()

In [62]:
df_num = df_ames_housing[num_cols].copy()

In [63]:
scaler_std = StandardScaler()
df_std = pd.DataFrame(
    scaler_std.fit_transform(df_num),
    columns=[f'padro_{col}' for col in num_cols],
    index=df_ames_housing.index
)

In [64]:
scaler_minmax = MinMaxScaler()
df_minmax = pd.DataFrame(
    scaler_minmax.fit_transform(df_num),
    columns=[f'norm_{col}' for col in num_cols],
    index=df_ames_housing.index
)

In [69]:
df_final = pd.concat([
    df_std,
    df_minmax
], axis=1)

In [70]:
df_final

,padro_Order,padro_PID,padro_MS SubClass,padro_Lot Frontage,padro_Lot Area,padro_Overall Qual,padro_Overall Cond,padro_Year Built,padro_Year Remod/Add,padro_Mas Vnr Area,...,norm_Garage Area,norm_Wood Deck SF,norm_Open Porch SF,norm_Enclosed Porch,norm_3Ssn Porch,norm_Screen Porch,norm_Pool Area,norm_Misc Val,norm_Mo Sold,norm_Yr Sold
0,-1.731460,-0.997164,-0.877005,3.072506,2.744381,-0.067254,-0.506718,-0.375537,-1.163488,0.056417,...,0.354839,0.147472,0.083558,0.0,0.0,0.000000,0.0,0.000000,0.363636,1.0
1,-1.730277,-0.996904,-0.877005,0.461265,0.187097,-0.776079,0.393091,-0.342468,-1.115542,-0.568996,...,0.490591,0.098315,0.000000,0.0,0.0,0.208333,0.0,0.000000,0.454545,1.0
2,-1.729095,-0.996899,-0.877005,0.504073,0.522814,-0.067254,0.393091,-0.441674,-1.259380,0.034081,...,0.209677,0.275983,0.048518,0.0,0.0,0.000000,0.0,0.735294,0.454545,1.0
3,-1.727913,-0.996888,-0.877005,1.017759,0.128458,0.641571,-0.506718,-0.110988,-0.779919,-0.568996,...,0.350806,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.272727,1.0
4,-1.726731,-0.992903,0.061285,0.204422,0.467348,-0.776079,-0.506718,0.848000,0.658466,-0.568996,...,0.323925,0.148876,0.045822,0.0,0.0,0.000000,0.0,0.000000,0.181818,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,1.726731,1.106582,0.530430,-1.379445,-0.280621,-0.067254,0.393091,0.418109,-0.012780,-0.568996,...,0.395161,0.084270,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.181818,0.0
2926,1.727913,1.106588,-0.877005,NaN,-0.160296,-0.776079,-0.506718,0.385040,-0.060726,-0.568996,...,0.325269,0.115169,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.454545,0.0
2927,1.729095,1.107245,0.647716,-0.309265,0.037199,-0.776079,-0.506718,0.682657,0.370789,-0.568996,...,0.000000,0.056180,0.043127,0.0,0.0,0.000000,0.0,0.041176,0.545455,0.0
2928,1.730277,1.110954,-0.877005,0.332844,-0.017506,-0.776079,-0.506718,0.087423,-0.444296,-0.568996,...,0.280914,0.168539,0.051213,0.0,0.0,0.000000,0.0,0.000000,0.272727,0.0
2929,1.731460,1.111225,0.061285,0.204422,-0.066118,0.641571,-0.506718,0.715726,0.466681,-0.044096,...,0.436828,0.133427,0.064690,0.0,0.0,0.000000,0.0,0.000000,0.909091,0.0